tutor_hub/ad/urls.py
'''
This program will create necessary html hyperlinks to show contents. 
'''
from django.urls import path
from . import views

urlpatterns = [
    path('find_tutor/', views.student_ad, name='find_tutor'),
    path('find_student/', views.tutor_ad, name='find_student'),
    path('home/', views.home, name='home'),
    path('profile/user/<int:user_pk>', views.ad_profile, name='profile_user'),
    path('my_ad/', views.my_ad, name='my_ad'),
    path('myAd/delete/student/post/<int:post_pk>', views.delete_post_student, name='delete_post_student'),
    path('myAd/delete/tutor/post/<int:post_pk>', views.delete_post_tutor, name='delete_post_tutor'),
]

tutor_hub/home/urls.py
'''
This program is for mapping the views and URLs
'''

from django.urls import path
from .import  views
from django.contrib.auth import views as auth_views

 
urlpatterns = [
    path('', views.landing, name='landing'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile_tutor/', views.edit_profile_tutor, name='edit_profile_tutor'),
    path('edit_profile_student/', views.edit_profile_student, name='edit_profile_student'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),

    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), 
        name="password_reset_complete"),

]
    
    

tutor_hub/tutor_hub/urls.py
from django.contrib import admin
from django.urls import path
from home import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import home
import courses
import mapbox
import ad

urlpatterns = [
    path('', include('details.urls')),
    path('', include('home.urls')),
    path('', include('ad.urls')),
    path('',include('courses.urls')),
    path('',include('mapbox.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),    
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tutor_hub/ad/models.py
'''
This program will create database file for Advertise feature.
'''
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse     

class AdStudent(models.Model):
    '''
    This is a conceptual Database representation of Class table for student ads.
    
    :param models.Model: It inherits built-in functionalities of django `models.Model`, which handels all validations in django Admin panel.
    :type models.Model: database model
    '''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150, null=True, blank=True)
    area = models.CharField(max_length=150, null=True, blank=True)
    subject = models.CharField(max_length=150, null=True, blank=True)
    class_level = models.CharField(max_length=150, null=True, blank=True)
    days = models.DecimalField(decimal_places=0, max_digits=2, default=2)
    salary = models.CharField(max_length=10,default=3000)
    male ='male'
    female = 'female'
    other = 'other'
    genders = [
        (male,'male'),
        (female,'female'),
        (other,'other'),
    ]
    gender = models.CharField(max_length=15, choices=genders,default=male,null=True,blank=True)
    description = models.TextField(null=True, blank=True)
    request_confirmation = models.BooleanField(default=False)
    ad_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        '''
        This will show the title of students's ad in the admin panel.
        
        :param self: Takes the self's variable name. 
        :type self: string
        :return: returns a reference to the instance object on which it was called.
        :rtype: model variable name
        '''
        return self.title

class AdTutor(models.Model):
    '''
    This is a conceptual Database representation of Class table for tutor ads.
    
    :param models.Model: It inherits built-in functionalities of django `models.Model`, which handels all validations in django Admin panel.
    :type models.Model: database model
    '''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150, null=True, blank=True)
    expected_area = models.CharField(max_length=150, null=True, blank=True)
    subject = models.CharField(max_length=150, null=True, blank=True)
    class_level = models.CharField(max_length=150, null=True, blank=True)
    days = models.DecimalField(decimal_places=0, max_digits=7, default=2)
    expected_salary = models.CharField(max_length=10,default=3000)
    male ='male'
    female = 'female'
    other = 'other'
    genders = [
        (male,'male'),
        (female,'female'),
        (other,'other'),
    ]
    gender = models.CharField(max_length=15, choices=genders,default=male,null=True,blank=True)
    description = models.TextField(null=True, blank=True)
    request_confirmation = models.BooleanField(default=False)
    ad_created = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        '''
        This will show the title of tutor's ad in the admin panel.
        
        :param self: Takes the self's variable name. 
        :type self: string
        :return: returns a reference to the instance object on which it was called.
        :rtype: self .model variable name
        '''
        return self.title
    
    
    

tutor_hub/ad/forms.py
'''
This program will create a django model form.
'''

from django import forms
from django.forms import ModelForm, fields
from .models import AdStudent, AdTutor


class AdStudentForm(ModelForm):
    '''
    This is a conceptual Form representation of Class table for student ads.
    :param ModelForm: It creates built-in html form of django, which handels all validations in django Admin panel.
    :type ModelForm: model, fields
    '''
    class Meta:
        model = AdStudent
        fields = '__all__'
        
class AdTutorForm(ModelForm):
    '''
    This is a conceptual Form representation of Class table for tutor ads.
    :param ModelForm: It creates built-in html form of django, which handels all validations in django Admin panel.
    :type ModelForm: model, fields
    '''
    class Meta:
        model = AdTutor
        fields = '__all__'
    

tutor_hub/home/forms.py
'''
This program will create a django model form.
'''

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django import forms
from django.forms import ModelForm
from home.models import Student,Tutor

class EditForm_Tutor(ModelForm):
    '''
    This is a conceptual Form representation of Class table for Tutor Profile
    
    :param ModelForm: It creates built-in html form of django, which handels all validations in django Admin panel.
    :type ModelForm: model, fields
    '''
    class Meta:
        model = Tutor
        fields = '__all__'
        exclude = ['user']
        
class EditForm_Student(ModelForm):
    '''
    This is a conceptual Form representation of Class table for Student Profile
    
    :param ModelForm: It creates built-in html form of django, which handels all validations in django Admin panel.
    :type ModelForm: model, fields
    '''
    class Meta:
        model = Student
        fields = '__all__'
        exclude = ['user']

class SignUpForm(UserCreationForm):
    '''
    This is a conceptual Form representation of Class table for user signup
    
    :param ModelForm: It creates built-in html form of django, which handels all validations in django Admin panel.
    :type ModelForm: model, fields
    '''
    first_name = forms.CharField(label='First Name', max_length=100)
    last_name = forms.CharField(label='Last Name', max_length=100)
    username = forms.CharField(label='Username', max_length=100)
    group = forms.ModelChoiceField(queryset=Group.objects.all(),required=True)
    email = forms.EmailField()
    class Meta:
        model = User

        labels = {
            'password1': 'Password',
            'password2': 'Confirm Password',
        }

        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'group']

tutor_hub/ad/views.py
'''
This program is the controller that fetch data from models.py and send it to the template file. 
'''
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from .models import AdStudent, AdTutor
from .forms import AdStudentForm, AdTutorForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from home.models import Student, Tutor
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# feature - 1


def student_ad(request):
    '''
    This will redirect the url to the student_ad page, where a logged in student can create a new post to find a tutor.
    
    :param request: Takes the request to show student_ad.html
    :type request: HttpResponse
    :return: returns a request for a html page with form data as dictonary format
    :rtype: render request,html page,dictonary
    '''
    User = get_user_model()
    users = User.objects.all()
    if request.method == 'GET':
        return render(request, 'ad/student_ad.html', {'form': AdStudentForm()})
    else:
        try:
            form = AdStudentForm(request.POST)
            form.save()
            return redirect('home')
        except ValueError:
            return render(request, 'ad/student_ad.html', {'form': AdStudentForm(), 'error': 'Limit is Crossed'})


def tutor_ad(request):
    '''
    This will redirect the url to the student_ad page, where a logged in tutor can create a new post to find a student.
    
    :param request: Takes the request to show tutor_ad.html
    :type request: HttpResponse
    :return: returns a request for a html page with form data as dictonary format
    :rtype: render request,html page,dictonary
    '''
    User = get_user_model()
    users = User.objects.all()
    if request.method == 'GET':
        return render(request, 'ad/tutor_ad.html', {'form': AdTutorForm()})
    else:
        try:
            form = AdTutorForm(request.POST)
            form.save()
            return redirect('home')
        except ValueError:
            return render(request, 'ad/tutor_ad.html', {'form': AdTutorForm(), 'error': 'Limit is Crossed'})


def home(request):
    '''
    This will redirect the url to the home page, where a logged in user can see posts of other user.
    
    :param request: Takes the request to show home.html
    :type request: HttpResponse
    :return: returns a request for a html page with form data as dictonary format
    :rtype: render request,html page,dictonary
    '''
    student_ad_list = AdStudent.objects.order_by('-ad_created')
    tutor_ad_list = AdTutor.objects.order_by('-ad_created')
    context = {}
    if "area" in request.GET:
        a = request.GET["area"]
        s = request.GET["salary"]
        sub = request.GET["subject"]
        g = request.GET["gender"]
        # result = Ad_Student.objects.filter(area__icontains=a)
        result_s = AdStudent.objects.filter(
            Q(area__icontains=a) & Q(salary__gte=s)
            & Q(subject__icontains=sub) & Q(gender=g))
        result_t = AdTutor.objects.filter(
            Q(expected_area__icontains=a) & Q(expected_salary__gte=s)
            & Q(subject__icontains=sub) & Q(gender=g))
        student_ad_list = result_s
        tutor_ad_list = result_t
        context['search'] = "search"

    # Paginator for Student Posts
    paginator = Paginator(student_ad_list, 5)
    page = request.GET.get('page')
    try:
        student_ads = paginator.page(page)
    except PageNotAnInteger:
        student_ads = paginator.page(1)
    except EmptyPage:
        student_ads = paginator.page(paginator.num_pages)

    # Paginator for Tutor Posts
    paginator = Paginator(tutor_ad_list, 5)
    page = request.GET.get('page')
    try:
        tutor_ads = paginator.page(page)
    except PageNotAnInteger:
        tutor_ads = paginator.page(1)
    except EmptyPage:
        tutor_ads = paginator.page(paginator.num_pages)

    context['student_ads'] = student_ads
    context['tutor_ads'] = tutor_ads

    return render(request, 'ad/home.html', context)

# feature - 2


@login_required
def my_ad(request):
    '''
    This will redirect the url to the myad page, where a user can see his own posts.
    
    :param request: Takes the request to show myad.html
    :type request: HttpResponse
    :return: returns a request for a html page with form data as dictonary format
    :rtype: render request,html page,dictonary
    '''
    myStudentAds = AdStudent.objects.filter(
        user=request.user).order_by('-ad_created')
    myTutorAds = AdTutor.objects.filter(
        user=request.user).order_by('-ad_created')
    return render(request, 'ad/myad.html', {'myStudentAds': myStudentAds, 'myTutorAds': myTutorAds})


@login_required
def delete_post_student(request, post_pk):
    '''
    This will redirect the url to the delete_post_student page, where a student can delete his own posts.
    
    :param request: Takes the request to show delete_post_student.html
    :type request: HttpResponse
    :param post_pk: Takes the id of the post to delete exact post
    :type post_pk: integer
    :return: returns a request for a html page with form data as dictonary format
    :rtype: render request,html page,dictonary
    '''
    student_post = AdStudent.objects.get(id=post_pk)
    if request.method == 'POST':
        student_post.delete()
        return redirect('my_ad')
    return render(request, 'ad/delete_post_student.html', {'student_post': student_post})


@login_required
def delete_post_tutor(request, post_pk):
    '''
    This will redirect the url to the delete_post_tutor page, where a tutor can delete his own posts.
    
    :param request: Takes the request to show delete_post_tutor.html
    :type request: HttpResponse
    :param post_pk: Takes the id of the post to delete exact post
    :type post_pk: integer
    :return: returns a request for a html page with form data as dictonary format
    :rtype: render request,html page,dictonary
    '''
    tutor_post = AdTutor.objects.get(id=post_pk)
    if request.method == 'POST':
        tutor_post.delete()
        return redirect('my_ad')
    return render(request, 'ad/delete_post_tutor.html', {'tutor_post': tutor_post})


@login_required
def ad_profile(request, user_pk):
    '''
    This will redirect the url to the ad_profile page, where a user can see other user's profile through ad.
    
    :param request: Takes the request to show delete_post_tutor.html
    :type request: HttpResponse
    :param post_pk: Takes the id of the user to redirect exact user's profile.
    :type post_pk: integer
    :return: returns a request for a html page with form data as dictonary format
    :rtype: render request,html page,dictonary
    '''
    User = get_user_model()
    user = User.objects.get(id=user_pk)
    return render(request, 'ad/ad_profile.html', {'user': user})

tutor_hub/ad/templates/ad/post_ad.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'post_ad.css' %}">
    <title>Post Ad</title>
</head>
<body>
  <nav>
    <input id="nav-toggle" type="checkbox">
    <div class="app_name">Tutor Hub</div>
    <ul>
        <li><a href="{% url 'home' %}">Back to Home</a></li>
    </ul>
    <label for="nav-toggle" class="three_lines">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
    </label>
  </nav>

    <div class="row justify-content-center mt-5">
      <div class="container post_ad">
        <h2 class="bg-info mb-3 text-center"> Fill this form to post your ad</h2>
      </div>
  </div>
  <div class="row justify-content-center mt-5">
      <div class="col-md-5">
          {% if error %}
              <div class="alert alert-danger" role="alert">
                  {{ error }}
              </div>
          {% endif %}
          <form method="POST"> 
            {% csrf_token %}
            <label for="id_user">User:</label> 
            <select class="form-control" name="user" required id="id_user">
              <option value="" selected>Select User</option>
              <option value="1">admin</option>
              <option value="5">faasd</option>
            </select>
            <div class="form-group">
              <label for="id_title">Title:</label> 
              <input type="text" class="form-control" name="title" maxlength="150"  placeholder="Write an Eye Catchy Title"  id="id_title">
            </div>
            <div class="form-group">
              <label for="id_area">Area:</label> 
              <input type="text" class="form-control" name="area" placeholder="Banani" maxlength="150" id="id_area">
            </div>
            <div class="form-group">
              <label for="id_subject">Subject:</label> 
              <input type="text" class="form-control" name="subject" placeholder="Physics / Accounting" maxlength="150" id="id_subject">
            </div>
            <div class="form-group">
              <label for="id_class_level">Class level:</label> 
              <input type="text" class="form-control" placeholder="Class 6 / O-Level" name="class_level" maxlength="150" id="id_class_level">
            </div>
            <div class="form-group">
              <label for="id_days">Days:</label> 
              <input type="number" min="0" class="form-control" name="days" placeholder="4" step="1" required id="id_days">
              <small class="text-muted ml-3"> Per Week </small>
            </div>
            <div class="form-group">
              <label for="id_salary">Salary:</label> 
              <input type="number" min="1000" class="form-control" name="salary" placeholder="5000 (min 1000)"  step="1e-1000" required id="id_salary">
              <small class="text-muted ml-3"> Taka </small>
            </div>
            <div class="form-group">
              <label for="id_gender">Gender:</label>
               <select name="gender" class="form-control" aria-label="Default select example" id="id_gender">
                  <option value="" selected>Select Gender</option>
                  <option value="male">male</option>
                  <option value="female">female</option>
                </select>
              </div>
            <div class="form-group">
              <label for="id_description">Description:</label> 
              <textarea name="description" class="form-control" cols="40" rows="10" id="id_description">
              </textarea>
            </div>
            <button type="submit" class="btn btn-primary align-self">Post Ad</button>

          </form>
      </div>
  </div>


    
</body>
</html>

tutor_hub/ad/templates/ad/student_ad.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'ad.css' %}">
    <title>Post Ad</title>
</head>
<body>
  <nav class="navbar nav navbar-expand-lg">
    <div class="app_name" href="#">Tutor Hub</div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'my_ad' %}">My Ad</a>
          </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}"> Back to Home</a>
        </li>
      </ul>
    </div>
  </nav>

    <div class="row justify-content-center mt-5">
      <div class="container post_ad">
        <h2 class="bg-info mb-3 text-center"> Fill this form to Find a Tutor</h2>
      </div>
  </div>
  <div class="row justify-content-center mt-5">
      <div class="col-md-5">
          {% if error %}
              <div class="alert alert-danger" role="alert">
                  {{ error }}
              </div>
          {% endif %}
          <form method="POST"> 
            {% csrf_token %}
          <label for="id_user">User:</label> 
            <select class="form-control" name="user" required id="id_user">
              <option value="{{user.id}}" selected>{{user.username}}</option>
            </select>
            <div class="form-group">
              <label for="id_title">Title:</label> 
              <input type="text" class="form-control" name="title" maxlength="150"  placeholder="Write an Eye Catchy Title"  id="id_title">
            </div>
            <div class="form-group">
              <label for="id_area">Area:</label> 
              <input type="text" class="form-control" name="area" placeholder="Banani" maxlength="150" id="id_area">
            </div>
            <div class="form-group">
              <label for="id_subject">Subject:</label> 
              <input type="text" class="form-control" name="subject" placeholder="Physics / Accounting" maxlength="150" id="id_subject">
            </div>
            <div class="form-group">
              <label for="id_class_level">Class level:</label> 
              <input type="text" class="form-control" placeholder="Class 6 / O-Level" name="class_level" maxlength="150" id="id_class_level">
            </div>
            <div class="form-group">
              <label for="id_days">Days:</label> 
              <input type="number" min="0" class="form-control" name="days" placeholder="4" step="1" required id="id_days">
              <small class="text-muted ml-3"> Per Week </small>
            </div>
            <div class="form-group">
              <label for="id_salary">Salary:</label> 
              <input type="number" min="1000" class="form-control" name="salary" placeholder="5000 (min 1000)"  step="1e-1000" required id="id_salary">
              <small class="text-muted ml-3"> Taka </small>
            </div>
            <div class="form-group">
              <label for="id_gender">Gender:</label>
               <select name="gender" class="form-control" aria-label="Default select example" id="id_gender">
                  <option value="" selected>Select Gender</option>
                  <option value="male">male</option>
                  <option value="female">female</option>
                </select>
              </div>
            <div class="form-group">
              <label for="id_description">Description:</label> 
              <textarea name="description" class="form-control" cols="40" placeholder="Write briefly about this ad or any special requirements" rows="10" id="id_description">
              </textarea>
            </div>
            <button type="submit" class="btn btn-primary align-self">Post Ad</button>

          </form>
      </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous"></script>
  
    
</body>
</html>

tutor_hub/ad/templates/ad/tutor_ad.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'ad.css' %}">
    <title>Post Ad</title>
</head>
<body>
    <nav class="navbar nav navbar-expand-lg">
        <div class="app_name" href="#">Tutor Hub</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my_ad' %}">My Ad</a>
              </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}"> Back to Home</a>
            </li>
          </ul>
        </div>
      </nav>

    <div class="row justify-content-center mt-5">
      <div class="container post_ad">
        <h2 class="bg-info mb-3 text-center"> Fill this form to Find a Student</h2>
      </div>
  </div>
  <div class="row justify-content-center mt-5">
      <div class="col-md-5">
          {% if error %}
              <div class="alert alert-danger" role="alert">
                  {{ error }}
              </div>
          {% endif %}
          <form method="POST"> 
            {% csrf_token %}
            <label for="id_user">User:</label>
            <select class="form-control" name="user" required id="id_user">
                <option value="{{user.id}}" selected>{{user.username}}</option>
              </select>
            <div class="form-group">
                <label for="id_title">Title:</label> 
                <input type="text" class="form-control"  name="title" maxlength="150"  placeholder="Write an Eye Catchy Title" id="id_title">
            </div>
            <div class="form-group">
                <label for="id_expected_area">Expected area:</label> 
                <input type="text" class="form-control"  name="expected_area" placeholder="Uttara" maxlength="150" id="id_expected_area">
            </div>
            <div class="form-group">
                <label for="id_subject">Subject:</label> 
                <input type="text" class="form-control" name="subject" placeholder="CSE 115" maxlength="150" id="id_subject">
            </div>
            <div class="form-group">
                <label for="id_class_level">Class level:</label> 
                <input type="text" class="form-control" name="class_level" placeholder="BSc." maxlength="150" id="id_class_level">
            </div>
            <div class="form-group">
                <label for="id_days">Days:</label> 
                <input type="number" class="form-control" name="days" placeholder="3" step="1" required id="id_days">
                <small class="text-muted ml-3">Per Week</small>
            </div>
            <div class="form-group">
                <label for="id_expected_salary">Expected salary:</label> 
                <input type="number" name="expected_salary" class="form-control" placeholder="3000"  step="1e-1000" required id="id_expected_salary">
                <small class="text-muted ml-3"> Taka </small>
            </div>
            <div class="form-group">
                <label for="id_gender">Gender:</label>
                <select name="gender" class="form-control" id="id_gender">
                    <option value="" selected>Select Gender</option>v
                    <option value="male">male</option>
                    <option value="female">female</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_description">Description:</label> 
                <textarea name="description" class="form-control" cols="40" placeholder="Write briefly about this ad or any special requirements" rows="10" id="id_description"></textarea>
            </div>
            <button type="submit" class="btn btn-primary align-self">Post Ad</button>
        </form>
    </div>
</div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous"></script>
          

</body>
</html>